# Generated by Django 4.2.7 on 2023-11-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_notified',
            field=models.IntegerField(default=None, null=True, verbose_name='last notified'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='to_notification',
            field=models.BooleanField(default=False),
        ),
    ]
