# Generated by Django 4.2.7 on 2023-11-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0003_customuser_last_notified_customuser_to_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='latitude',
            field=models.IntegerField(null=True, verbose_name='lat'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longitude',
            field=models.IntegerField(null=True, verbose_name='long'),
        ),
    ]
